language: csharp
sudo: required
mono: none
dotnet: 2.2
dist: xenial
cache:
  yarn: true 
  directories:
    - $HOME/.nuget/packages
    - $HOME/.chakracore
before_install:
  - bash scripts/install_protobuf.sh
  - nvm install node
  - npm install -g yarn
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - export LD_LIBRARY_PATH=$HOME/.chakracore/1_11_1/:$LD_LIBRARY_PATH
  - bash scripts/install_chakracore.sh 1_11_1
script:
  - bash scripts/build.sh
  - bash scripts/test.sh
after_script:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "./results/coverage.opencover.xml" -t $CODECOV_TOKEN
deploy:
  - provider: script
    script:
      - bash scripts/publish_docker.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
      - bash scripts/publish_nuget.sh  $TRAVIS_TAG $NUGET_API_KEY
    skip_cleanup: true
    on:
      tags: true
