language: csharp
sudo: required
mono: none
dotnet: 3.1.100
dist: xenial
os:
  - linux
  - osx
osx_image: xcode11
cache:
  directories:
    - $HOME/.nuget/packages
env:
  global:
    - REAL_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")
    - CI_TEST=true
before_install:
  - bash scripts/install_protobuf.sh
  - bash scripts/download_binary.sh
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
script:
  - dotnet tool install --global Cake.Tool
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - export PATH="$HOME/.dotnet:$PATH"
  - dotnet tool restore
  - dotnet tool install --global coverlet.console
  - dotnet cake ./build.cake --target=build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet cake build.cake --target=test ; fi
after_script:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./codecov -f "./test/results/coverage.opencover.xml" -t $CODECOV_TOKEN          ; fi 
