language: csharp
mono: none
dotnet: 2.0.2
dist: trusty
branches:
  only:
  - master
install:
 - dotnet restore -s "https://nuget.cnblogs.com/v3/index.json" -s "https://api.nuget.org/v3/index.json" "AElf.sln"
before_script:
 - dotnet test "AElf.Kernel.Tests/AElf.Kernel.Tests.csproj"
script:
 - dotnet build "AElf.Kernel/AElf.Kernel.csproj"
 
 