language: csharp
sudo: required
mono: none
dotnet: 2.2
dist: xenial
before_install:
  - bash scripts/install_protobuf.sh
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - bash scripts/download_chakracore.sh 1_11_1
  - export LD_LIBRARY_PATH=$(pwd)/ChakraCoreFiles/lib/:$LD_LIBRARY_PATH
script:
  - bash scripts/build.sh
deploy:
  - provider: script
    script: bash scripts/deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on:
      tags: true
