jobs:
# All tasks on Windows....
- job: build_all_windows
  displayName: Build all tasks (Windows)
  timeoutInMinutes: 120
  pool:
    vmImage: windows-2019
  variables:
    CI_TEST: true
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.102'
  - script: choco install protoc --version=3.11.4 -y
  - script: choco install unzip
  - task: BatchScript@1
    inputs:
      filename: 'scripts/download_binary.bat'
  - script: PowerShell.exe -file build.ps1 -target=Test-with-Codecov
    displayName: 'Build and Test'
  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . dotnet-reportgenerator-globaltool
    displayName: Install ReportGenerator tool
  - script: PowerShell.exe -file build.ps1 -target=Clean
    displayName: 'Clean'
  - script: reportgenerator -reports:$(Build.SourcesDirectory)/test/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/test/results -reporttypes:"Cobertura"
    displayName: Create reports
    
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/test/results/Cobertura.xml
      reportDirectory: '$(Build.SourcesDirectory)/test/results'
  
  - script: PowerShell.exe -file build.ps1 -target=Upload-Coverage
    displayName: 'Upload data to Codecov'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.102'
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - script: bash build.sh
    displayName: 'Build and Test'
# All tasks on macOS
- job: build_all_darwin
  displayName: Build all tasks (macOS)
  pool:
    vmImage: macos-10.13
  variables:
    CI_TEST: true
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.102' 
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - script: bash build.sh
    displayName: 'Build and Test'
