jobs:
# All tasks on Windows....
- job: build_all_windows
  displayName: Build all tasks (Windows)
  timeoutInMinutes: 120
  pool:
    vmImage: windows-latest
  variables:
    CI_TEST: true
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 3.1.102
  - script: choco install protoc --version=3.11.4 -y
    displayName: 'Install protobuf'
  - script: choco install unzip
    displayName: 'Install unzip'
  - task: BatchScript@1
    displayName: 'Download AElf build tools'
    inputs:
      filename: 'scripts/download_binary.bat'
  - script: PowerShell.exe -file build.ps1 -target=Test-with-Codecov
    displayName: 'Build and Test'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 3.1.102
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - script: bash build.sh
    displayName: 'Build and Test'
# All tasks on macOS
- job: build_all_darwin
  displayName: Build all tasks (macOS)
  pool:
    vmImage: macos-latest
  variables:
    CI_TEST: true
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 3.1.102
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - script: bash build.sh
    displayName: 'Build and Test'
