jobs:

# All tasks on Windows....
- job: build_all_windows
  displayName: Build all tasks (Windows)
  pool:
    vmImage: windows-2019
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.100'
  - script: choco install protoc --version 3.6.0 -y
  - script: choco install unzip
  - task: BatchScript@1
    inputs:
      filename: 'scripts/download_binary.bat'
      #  - script: dotnet tool install --global cake.tool --version 0.35.0
  - script: PowerShell.exe -file build.ps1
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.100'
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - script: dotnet tool install --global Cake.Tool --version 0.35.0
    displayName: 'Install "Cake.Tool" .NET Core global tool'
  - script: export PATH="$PATH:$HOME/.dotnet/tools"
  - script: export PATH="$HOME/.dotnet:$PATH"
  - script: dotnet tool restore
  - script: dotnet tool install --global coverlet.console
  - script: dotnet cake ./build.cake 
# All tasks on macOS
- job: build_all_darwin
  displayName: Build all tasks (macOS)
  pool:
    vmImage: macos-10.13
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.100' 
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - script: dotnet tool install --global Cake.Tool --version 0.35.0
    displayName: 'Install "Cake.Tool" .NET Core global tool'
  - script: export PATH="$PATH:$HOME/.dotnet/tools"
  - script: export PATH="$HOME/.dotnet:$PATH"
  - script: dotnet tool restore
  - script: dotnet tool install --global coverlet.console
  - script: dotnet cake ./build.cake
