jobs:

# All tasks on Windows....
- job: build_all_windows
  displayName: Build all tasks (Windows)
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: UseDotNet@2
    inputs:
      version: '2.2.300'
  - script: choco install protoc --version 3.6.0 -y
  - script: choco install 7zip 7zip.install
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'AElf.sln'
      arguments: '/clp:ErrorsOnly /p:GeneratePackageOnBuild=false'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'AElf.sln'

# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: UseDotNet@2
    inputs:
      version: '2.2.300'
  - script: sudo apt update
  - script: bash scripts/install_protobuf.sh
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'AElf.sln'
      arguments: '/clp:ErrorsOnly /p:GeneratePackageOnBuild=false'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'AElf.sln'

# All tasks on macOS
- job: build_all_darwin
  displayName: Build all tasks (macOS)
  pool:
    vmImage: macos-10.13
  steps:
  - task: UseDotNet@2
    inputs:
      version: '2.2.300' 
  - script: sudo apt update
  - script: bash scripts/install_protobuf.sh
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'AElf.sln'
      arguments: '/clp:ErrorsOnly /p:GeneratePackageOnBuild=false'
